upstreams:
  groups:
    default:
      - https://dns.cloudflare.com/dns-query
      - https://dns.quad9.net/dns-query
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
  clientGroupsBlock:
    default:
      - ads
ports:
  dns: 53
  http: 4000
